### ISSUE TITLE
feedback 1

### ISSUE THREAD

**Issue by Nazerek** [ARMSLab/observability_measure.github.io#3]
I got the general idea but did not understand some formulas(therefore its coding part was not clear for me) .  We don't usually solve such problems in Matlab , therefore I have to recall it and spend more time on reading the tutorial.   This tutorial definitely is not for 2nd year student. But another tutorial on Linearized MPC controller is more understandable. I think that is because of the graphical illustrations.   I will try to read it again and then I will write a more detailed feedback

**Comment by bexultanrakhim** [comment]
done
